### PR TITLE
Partial ghc 7.10 support

### PR DESCRIPTION
**Pull request by hesselink**
I updated `hxt-regex-xmlschema` and `hxt` to compile with GHC 7.10. `hxt-charproperties` and `hxt-unicode` also compile unchanged. There are still many warnings, and I haven't tested the other packages.

### CODE REVIEW

**Comment by hvr** [comment]
What's the status of this? This currently blocks `gl` from being usable with GHC 7.10.1RC2

**Comment by UweSchmidt** [comment]
I've tried to compile hxt with ghc-7.10.1-RC2, but `cabal install` gives a lot of errors, like e.g.

`
on the commandline: Warning:
    -package-name is deprecated: Use -this-package-key instead
ghc: ghc no longer supports single-file style package databases (dist/package.conf.inplace) use 'ghc-pkg init' to create the database with the correct format.
`

any hints what goes wrong?
ghc is installed in a local subdir `~/local/ghc-7.10.1` and `PATH` includes this dir as the first one.

**Comment by hvr** [comment]
@UweSchmidt you also need a more recent `cabal-install` executable; try with the latest 1.22 version from Hackage...

**Comment by hesselink** [comment]
Thanks, so I'll close this one.

**Pull request closed without merging**
